server:
  context-path: /demo
  port: 9030
  compression:
    enabled: true
  error:
      path: /error

cas:
  clientName: demo-clientName
  prefixUrl: http://10.56.69.71/sso
  loginUrl: ${cas.prefixUrl}/login
  logoutUrl: ${cas.prefixUrl}/logout
  serviceUrl: http://localhost:${server.port}${server.context-path}
  callbackUrl: ${cas.serviceUrl}/callback
  unauthorizedUrl: /403

  logout:
    followServiceRedirects: true


## 开发/测试/生产环境分别对应dev/test/prd
spring:
  profiles:
    active: prd
#  aop:
#    proxy-target-class: true
  #静态资源的配置
  resources:
    cache-period: 10000
    chain:
      gzipped: true
      cache: true
  #mvc: 
    #static-path-pattern: /**
    #view: 
      #prefix: /
      #suffix: .html,.do

  #freemarker
  freemarker: 
    request-context-attribute: request

  #session
  session:
    store-type: redis

#logging
logging:
  level:
    org:
      springframework:
        web: INFO
  file: web.log
  
