server:
  context-path: /demo
  port: 9030
  compression:
    enabled: true
  error:
      path: /error

cas:
  logout:
    followServiceRedirects: true


## 开发/测试/生产环境分别对应dev-bill/test/prd-mss/prd-bill
spring:
  profiles:
    active: prd-bill
#  aop:
#    proxy-target-class: true
  #静态资源的配置
  resources:
    cache-period: 10000
    chain:
      gzipped: true
      cache: true
  #mvc: 
    #static-path-pattern: /**
    #view: 
      #prefix: /
      #suffix: .html,.do

  #freemarker
  freemarker: 
    request-context-attribute: request

  #session
  session:
    store-type: redis

#logging
logging:
  level:
    org:
      springframework:
        web: INFO
  file: springboot-demo.web.log
  
